### ISSUE TITLE
Display image functionality is broken

### ISSUE THREAD

**Issue by rahul-2-c** [hvijay3/Piccolo#35] opened 2017-11-24 04:00 UTC
Steps to reproduce:
1) Click on any image on imagelist. 
2) Click on Imagelist and select any other image.
Ideally only the new image should be displayed, but the entire imagelist is also displayed along with the selected image.

**Comment by hvijay3** [comment] 2017-11-24 04:47
Resolved in commit 55736af67d7aaf168aba9170b7fa7ea2edf7dbb3.

**Comment by 19ankits** [comment] 2017-11-24 22:32
Fix in commit 55736af, is breaking another feature now. **ImageList in the Nav-Bar is broken now**

**Earlier:** After searching and entering other user's profile, the logged in user can return to his own dashboard by single click of "ImageList" in the Nav-bar.

**Now:** After replacing the "href", with "routerLink", this is broken.

**Suggestion:** Lets do the root cause analysis and pin point the commit that caused the original issue in first place. The last commit till the UID-Username mapping under branch "ankit" works perfect and nothing ain't broken. All commits above that need to be investigated.

**Original Issue:** Display image functionality is broken

**Before Pushing:** Send out for reviews and functional testing.

**Comment by hvijay3** [comment] 2017-11-24 23:26
The issue is that we are trying to navigate to a component from itself . After searching user the flow is first other user component and then image list component. So if we click on image list it tries to navigate back to imgae list component but we are already there.
To resolve it. We can put a home button whenever we are in other user profile . This will take it to home component which will then route it to image list component of logged in user.

**Comment by hvijay3** [comment] 2017-11-24 23:30
So both href and router link will create problems .
**If we use href tag** :  Since href does not navigate to a component . It will work for navigation ( from image list component to a url link) but will create problems while rendering as noted by rahul initially i.e when you go to an image component and then try to navigate to image list component. It will take you to a url link not component.  Son in browser you will see both image and image list together.
**Router link** : Router link will create navigation problem from same component .
 So a middle solution is routing the navigation through other component ( home component)

**Comment by 19ankits** [comment] 2017-11-24 23:41
_**Putting it all here for the sake of one stop discussions.**_

On using "href", system did work fine ie navigating from other user's profile to logged in user's own profile without any issues. This is technically same as returning to one's own profile. Isn't it?

ImageList is nothing but a home button only (functionality-wise), ignoring the literally meaning for a second.

Try to pull my branch and test locally, it will work exactly same as a home functionality via the ImageList. Agree that we are activating the same component but a different navigation distinguished by the user_id.

**Comment by 19ankits** [comment] 2017-11-24 23:41
Moreover, using "routerLink" instead of existing "href" doesn't fix the issue. Below are the steps to reproduce it.

- Click on an Image.
- Hit Refresh in the browser.
- Click on ImageList.

**Comment by 19ankits** [comment] 2017-11-24 23:49
Few Points:

- Just curious, why was it not creating problems while rendering untill now with comment feature already added long back and is breaking now with just the authors, timestamp and styling as addition? 
- Weren't we going to image component and then navigating to ImageList component earlier too and browser would show just the **ImageList and not the Image**

- Adding home component seems redundant and should be the last resort in that case. What do you think? Let me know your inputs.

**Comment by hvijay3** [comment] 2017-11-24 23:55
According to rahul , to reproduce the error when using href :
Click on any image on imagelist.
Click on Imagelist and select any other image.
Ideally only the new image should be displayed, but the entire imagelist is also displayed along with the selected image.

The issue is noted later. So yes the issue was there after href, only we didn't observe it. 

**Adding home component seems redundant and should be the last resort in that case. What do you think? Let me know your inputs.**
Home component is already present. We need to add a home button . Could be done. Just have to navigate on click. No other option I see as we have to navigate it to other component first to get to image component. Suggest if any other alternative!!

**Comment by 19ankits** [comment] 2017-11-25 00:01
**The issue is noted later. So yes the issue was there after href, only we didn't observe it.**

Did you try to pull the branch "ankit" (bb51059) and were you able to reproduce it? 
I tried so and it works perfect with no issues and just the image being clicked is getting displayed and not the entire ImageList.

**Comment by hvijay3** [comment] 2017-11-25 00:08
I am getting dependencies error if trying to run your branch copy . Ok if the error is not coming then suggest alternatives !!. As according to me the reason of error was we trying to navigate from a url to a component.

**Comment by hvijay3** [comment] 2017-11-25 00:12
What is the last commit when issue was not there . I mean the last commit in your branch?

**Comment by 19ankits** [comment] 2017-11-25 00:15
b75177a

I'm not getting any dependency errors, not sure whats causing the error for you.

**Comment by hvijay3** [comment] 2017-11-25 00:17
Yes i checked . You are right. Issue was not present before . Looks weird what's the cause then !! As changing href to router link fixed the rendering problem but why it didn't occur before. Have to see rahul changes then !!

**Comment by rahul-2-c** [comment] 2017-11-25 00:23
I will look into the changes pushed by me to check for any dependency on existing code-base.

**Comment by 19ankits** [comment] 2017-11-25 00:25
A general consensus should be to not push anything to remote repository untill we test the functionalities and ensure that it doesn't break anything from past commits. If for any reason we do, lets stick back to start from the last working commit.

Meanwhile I'd push the changes for search and follow/unfollow on top of the last working commit.

**Comment by 19ankits** [comment] 2017-11-25 00:28
**changing href to router link fixed the rendering problem**

This actually didn't fix the issue but did hide :). You can reproduce it by following the below steps:

- Click on an Image.
- Hit Refresh in the browser.
- Click on ImageList.

Anyway, ignore it!

**Comment by 19ankits** [comment] 2017-11-30 13:42
Adding extra navigation via Home component fixed the problem, hence closing the issue.

**Closed as completed by 19ankits** 2017-11-30 13:42 UTC
Labels: bug
